import pg from "pg";

const { Pool } = pg;
const pool = new Pool({
  connectionString:
    "postgresql://postgres:password@localhost:5432/drama_tracker",
});

const TYPE_MAP = {
  M: "MOVIE",
  S: "SERIES",
  A: "ANIME",
  V: "VARIETY",
  W: "WEB_DRAMA",
};

const RAW = {
  KOREAN: [
    ["18 Again", "S", [], `C`],
    ["200 Pounds Beauty", "M", [], `C`],
    ["Abyss", "S", ["N"], `C`],
    ["A Gentleman's Dignity", "S", [], `C`],
    ["A Frozen Flower", "S", [], `C`],
    ["A Killer Paradox", "S", [], `C`],
    ["Angry Mom", "S", [], `C`],
    ["Another Oh Hae Young", "S", [], `C`],
    ["A Thousand Kisses", "S", [], `C`],
    ["A Well-Grown Daughter", "S", [], `C`],
    ["A Werewolf Boy", "S", [], `C`],
    ["A Witch's Romance", "S", [], `C`],
    ["Baby and I", "M", [], `C`],
    ["Baby Faced Beauty", "S", ["S"], `C`],
    ["Baker King, Kim Tae Goo", "S", [], `C`],
    ["Beak Hee Has Returned", "S", [], `C`],
    ["Beautiful Man", "S", ["I"], `C`],
    ["Because I Love You", "M", [], `C`],
    ["Because This Is My First Life", "S", ["S"], `C`],
    ["Behind Your Touch", "S", ["H"], `C`],
    ["Birth of a Beauty", "S", [], `C`],
    ["Blood", "S", ["I"], `C`],
    ["Bo Tu Lua Dao", "M", [], `C`],
    ["Bomi's Room", "M", [], `C`],
    ["Borg Mom", "S", [], `C`],
    ["Boys Over Flowers", "S", ["S", "I"], `C`],
    ["Brave Citizens", "M", [], `C`],
    ["Business Proposal", "S", [], `P,ep 9`],
    ["Blueming", "S", [], `C`],
    ["Call", "M", [], `C`],
    ["Cafe Minamdang", "S", [], `P,ep 11`],
    ["Can You Hear My Heart", "S", ["S"], `C`],
    ["Celebrity", "S", [], `C`],
    ["Cheese in the Trap", "S", ["S", "I"], `C`],
    ["Cheongdamdong Alice", "S", [], `C`],
    ["Chief Kim", "S", ["H"], `C`],
    ["Chuyện Tình Bong Bóng", "S", [], `C`],
    ["Chuyện Tình Mũm Mĩm", "W", [], `C`],
    ["Cinderella and Four Knights", "S", ["S", "I"], `C`],
    ["City Hunter", "S", [], `C`],
    ["Code Name: Jackal", "M", [], `C`],
    ["Coffee, Please", "S", [], `C`],
    ["Coffee Prince", "S", [], `C`],
    ["Collective Invention", "M", [], `C`],
    ["Confession", "M", [], `C`],
    ["Couple or Trouble", "S", ["H"], `C`],
    ["Crash Course in Romance", "S", ["I"], `C`],
    ["Crash Landing on You", "S", [], `P,ep 11`],
    ["Cunning, Single Lady", "S", ["S", "I"], `C`],
    ["Cyrano Agency", "M", [], `C`],
    ["Daddy You, Daughter Me", "M", [], `C`],
    ["Dating Agency: Cyrano", "S", ["I"], `C`],
    ["Dear Fair Lady Gong Shim", "S", ["H"], `C`],
    ["Dear My Friends", "S", [], `C`],
    ["Dear X", "S", [], `P,ep 6`],
    ["Death Bell", "M", [], `C`],
    ["Divorce Lawyer in Love", "S", [], `C`],
    ["Doctor Cha", "S", [], `C`],
    ["Don't Worry, I'm a Ghost", "S", [], `C`],
    ["Doubt", "S", [], `C`],
    ["Dr. Romantic 2", "S", [], `C`],
    ["Dr. Romantic 3", "S", [], `C`],
    ["Emergency Couple", "S", ["N"], `C`],
    ["Ex-Girlfriend Club", "S", [], `C`],
    ["Extraordinary You", "S", ["S"], `C`],
    ["Fated to Love You", "S", [], `C`],
    ["Fight for My Way", "S", [], `C`],
    ["Find Me in Your Memory", "S", [], `C`],
    ["First Kiss for the Seventh", "S", [], `C`],
    ["Five Enough", "S", [], `C`],
    ["Five Senses of Eros", "S", [], `C`],
    ["Flower Boy Next Door", "S", ["S"], `C`],
    ["Flower Boy Ramen Shop", "S", ["S", "H"], `C`],
    ["Forgotten", "M", [], `C`],
    ["Full House", "S", ["I"], `C`],
    ["Full House Take 2", "S", ["S", "I"], `C`],
    ["Go Back Couple", "S", ["S"], `C`],
    ["Goblin", "S", ["H"], `C`],
    ["Goong", "S", ["S", "I"], `C`],
    ["Heartstrings", "S", ["I"], `C`],
    ["Hello Ghost", "M", ["H"], `C`],
    ["Her Private Life", "S", ["S", "I"], `C`],
    ["High Kick Through the Roof 2", "S", [], `C`],
    ["High School Love On", "S", ["S"], `C`],
    ["Hogu's Love", "S", [], `C`],
    ["Hope for Love", "S", [], `C`],
    ["Hospital Playlist", "S", [], `C`],
    ["Hotel del Luna", "S", ["S"], `C`],
    ["Hyde, Jekyll, Me", "S", ["S", "I"], `C`],
    ["I Do, I Do", "S", ["S"], `C`],
    ["I Picked Up a Celebrity on the Street", "S", [], `C`],
    ["Infinity Challenge", "V", [], `C`],
    ["Inspector Koo", "S", [], `C`],
    ["Inseparable Brothers", "M", [], `C`],
    ["It's Okay, It's Love", "S", ["N"], `C`],
    ["It's Okay Not to Be Okay", "S", [], `C`],
    ["Jealousy Incarnate", "S", ["S", "I"], `C`],
    ["Juvenile Justice", "S", [], `C`],
    ["Kill Bok Soon", "M", [], `C`],
    ["Kill Me, Heal Me", "S", ["S", "H"], `C`],
    ["King of High School", "S", [], `C`],
    ["King The Land", "S", [], `P,ep 8`],
    ["Korean Odyssey", "S", ["I"], `C`],
    ["Level Up", "S", [], `C`],
    ["Likes for Likes", "M", [], `C`],
    ["Live", "S", [], `C`],
    ["Love and Leashes", "M", [], `C`],
    ["Love Forecast", "M", [], `C`],
    ["Lovely Horribly", "S", ["S", "I"], `C`],
    ["Love to Hate You", "S", [], `C`],
    ["Love With Flaws", "S", ["S"], `C`],
    ["Lucky Romance", "S", ["S", "H", "I"], `C`],
    ["Mad for Each Other", "S", [], `C`],
    ["Mask Girl", "S", [], `C`],
    ["Man Living at My House", "S", [], `C`],
    ["Marriage, Not Dating", "S", ["S", "I"], `C`],
    ["Master's Sun", "S", ["I"], `C`],
    ["Me Too, Flower", "S", [], `C`],
    ["Midnight Runners", "M", ["H"], `C`],
    ["Miracle in Cell No. 7", "M", [], `C`],
    ["Moorim School", "S", ["S", "I"], `C`],
    ["Mouse", "S", ["S"], `C`],
    ["Mr. Back", "S", ["I"], `C`],
    ["Mr. Queen", "S", ["H", "N"], `C`],
    ["My Annoying Brother", "M", [], `C`],
    ["My Boyfriend is Type B", "M", [], `C`],
    ["My Dearest Nemesis", "S", [], `C`],
    ["My Father is Strange", "S", ["H", "N"], `C`],
    ["My Girl", "S", ["S", "I"], `C`],
    ["My Good Bad Mother", "S", [], `C`],
    ["My Girlfriend is Gumiho", "S", ["H", "N"], `C`],
    ["My Happy Home", "M", [], `C`],
    ["My Husband, Mr. Oh", "S", [], `P,ep 13`],
    ["My ID is Gangnam Beauty", "S", ["N"], `C`],
    ["My Love from the Star", "S", ["I"], `C`],
    ["My Secret Hotel", "S", [], `C`],
    ["My Secret Romance", "S", ["N"], `C`],
    ["My Sister, the Pig Lady", "M", [], `C`],
    ["My Wife is Having an Affair", "S", [], `C`],
    ["Mystic Pop-up Bar", "S", [], `C`],
    ["Ngày Không Còn Mẹ", "M", [], `C`],
    ["Nice Guy", "S", [], `C`],
    ["Nightmare High", "S", [], `C`],
    ["Officer Black Belt", "M", [], `C`],
    ["Ohlala Couple", "S", ["S", "I"], `C`],
    ["Oh My Ghost", "S", ["I", "N"], `C`],
    ["Oh My Venus", "S", ["I"], `C`],
    ["One More Happy Ending", "S", ["S"], `C`],
    ["On Your Wedding Day", "M", [], `C`],
    ["Our Beloved Summer", "S", ["N"], `C`],
    ["Page Turner", "S", [], `C`],
    ["Penny Pinchers", "M", [], `C`],
    ["Pinocchio", "S", ["N"], `C`],
    ["Pinocchio's Nose", "M", [], `C`],
    ["Playful Kiss", "S", ["S", "I"], `C`],
    ["Please Come Back Mister", "S", [], `C`],
    ["Physical 100", "V", [], `C`],
    ["Potato Star", "S", ["S"], `C`],
    ["Prime Minister and I", "S", [], `C`],
    ["Producer", "S", [], `C`],
    ["Protect the Boss", "S", ["I", "N"], `C`],
    ["Puck", "S", [], `C`],
    ["Queen In Hyun's Man", "S", ["N"], `C`],
    ["Queen of Tears", "S", [], `C`],
    ["Radiant Office", "S", ["I"], `C`],
    ["Reply 1988", "S", ["S"], `C`],
    ["Rooftop Prince", "S", ["I", "N"], `C`],
    ["Running Man", "V", [], `C`],
    ["School 2013", "S", [], `C`],
    ["School 2017", "S", ["N"], `C`],
    ["Second Time Twenty Years Old", "S", [], `C`],
    ["Second to Last Love", "S", [], `C`],
    ["Secret Garden", "S", ["I", "N"], `C`],
    ["Secret Love", "S", ["I"], `C`],
    ["Semantic Error", "S", ["N", "I"], `C`],
    ["Seventeen", "W", ["N"], `C`],
    ["She Was Pretty", "S", ["S", "I"], `C`],
    ["Shooting Star", "S", [], `C`],
    ["Sound of Your Heart", "S", [], `C`],
    ["Speed Scandal", "M", [], `C`],
    ["Splash Splash Love", "S", ["I", "N"], `C`],
    ["Strange Fairy Tales", "M", [], `C`],
    ["Strong Girl Nam Soon", "S", [], `P,ep 10`],
    ["Super Daddy Yeol", "S", [], `C`],
    ["Sweden Laundry", "S", [], `C`],
    ["Sweet and Sour", "M", [], `C`],
    ["Tale of Nokdu", "S", [], `C`],
    ["Tempest", "S", [], `C`],
    ["The Beauty Inside", "M", [], `C`],
    ["The Beauty Inside (Drama)", "S", ["I"], `C`],
    ["The Bros", "M", [], `C`],
    ["The Brothers' Summer", "M", [], `C`],
    ["The Descendant of the Sun", "S", ["N"], `C`],
    ["The Devil Plan", "V", [], `C`],
    ["The Dude in Me", "M", [], `C`],
    ["The Eccentric Daughter-in-Law", "S", [], `C`],
    ["The Heirs", "S", ["S"], `C`],
    ["The Legendary Lackey", "M", [], `C`],
    ["The Law Cafe", "S", [], `C`],
    ["The Lover", "S", [], `C`],
    ["The Match", "M", [], `C`],
    ["The Miracle", "S", [], `C`],
    ["The Plan Man", "M", [], `C`],
    ["The Player", "S", [], `C`],
    ["The Reason I'm Getting Married", "M", [], `C`],
    ["The Red Teacher", "M", [], `C`],
    ["The Scent of a Woman", "S", ["I"], `C`],
    ["The Secret Life of My Secretary", "S", [], `C`],
    ["The Strongest Delivery Man", "S", ["S"], `P,ep 5`],
    ["The Switch", "M", [], `C`],
    ["The Three Female Runaways", "M", [], `C`],
    ["The Uncanny Counter", "S", [], `C`],
    ["The Unlocked", "M", [], `C`],
    ["The Worst of Evil", "S", [], `C`],
    ["Thirty but Thirteen", "S", [], `C`],
    ["Tình Yêu Đơn Phương", "W", [], `C`],
    ["Tomorrow", "S", [], `C`],
    ["Too Beautiful to Lie", "M", [], `C`],
    ["Touch Your Heart", "S", [], `C`],
    ["Train to Busan", "M", [], `C`],
    ["Trot Lovers", "S", [], `C`],
    ["Twenty", "M", [], `C`],
    ["Twenty Again", "S", [], `C`],
    ["Two Weddings and a Funeral", "M", [], `C`],
    ["Vigilante", "S", [], `C`],
    ["W - Two Worlds", "S", [], `C`],
    ["Was It Love", "S", [], `C`],
    ["What a Man Wants", "M", [], `C`],
    ["What Is the Ghost Up To?", "M", [], `C`],
    ["What on Earth Is Going On?", "S", [], `C`],
    ["Welcome to Samdal-ri", "S", ["N"], `C`],
    ["Wild Romance", "S", ["I"], `C`],
    ["Witch's Love", "S", [], `C`],
    ["Wonderful Nightmare", "M", [], `C`],
    ["Wonderful Radio", "M", [], `C`],
    ["You Call It Passion", "M", [], `C`],
    ["You're Beautiful", "S", ["S", "I"], `C`],
  ],
  THAI: [
    ["15 Coming of Age", "M", [], `C`],
    ["3 Chàng Trai Vàng", "S", [], `C`],
    ["46 Days", "S", [], `C`],
    ["A Tale of Thousand Stars", "S", ["N"], `C`],
    ["Back to the 90s", "M", [], `C`],
    ["Bad Buddy", "S", ["H"], `C`],
    ["Be My Favorite", "S", [], `C`],
    ["Boy For Rent", "S", ["I"], `C`],
    ["Cặp Đôi Cay Như Ớt", "S", ["I"], `C`],
    ["Cậu Chủ Về Vườn", "S", ["I"], `C`],
    ["Cause You Are My Boy", "S", [], `C`],
    ["Chỉ Có Tình Yêu", "S", [], `C`],
    ["Chuyện Tình Nangthip", "S", ["S"], `C`],
    ["Club Friday S6: Best Friend 1", "S", [], `C`],
    ["Club Friday S6: Best Friend 2", "S", [], `C`],
    ["Cô Nàng Điện Giật", "M", ["S"], `C`],
    ["Cô Vợ Ma", "M", [], `C`],
    ["Dark Blue Kiss", "S", ["I"], `C`],
    ["Enchante", "S", [], `C`],
    ["Fish Upon The Sky", "S", [], `C`],
    ["FriendZone 1", "S", [], `C`],
    ["Girl Next Room: Midnight Fantasy", "S", [], `C`],
    ["Girl Next Room: Richy Rich", "S", [], `C`],
    ["He's Coming to Me", "S", [], `C`],
    ["KinnPorsche", "S", [], `C`],
    ["Kiss Me Again", "S", ["I"], `C`],
    ["Khun Chai", "S", [], `C`],
    ["Law of Attraction", "S", [], `C`],
    ["Love Arumi Like", "M", [], `C`],
    ["Love Beyond Frontier", "S", [], `C`],
    ["Love Bipolar", "S", [], `C`],
    ["Love Sick 1", "S", [], `C`],
    ["Love Sick 2", "S", [], `C`],
    ["Lovey Dovey", "S", ["S"], `C`],
    ["Lừa Tình", "S", ["I"], `C`],
    ["Malee The Series", "S", [], `C`],
    ["Mệnh Lệnh Thần Tình Yêu", "S", [], `C`],
    ["Nàng Dâu Hoàng Gia", "S", ["I", "N"], `C`],
    ["Người Con Gái Tôi Yêu", "S", [], `C`],
    ["Nhẫn Hoa Tình Yêu", "S", [], `C`],
    ["Only Friends", "S", [], `C`],
    ["Ourskyy", "S", [], `C`],
    ["Perfect 10 Liners", "S", [], `C`],
    ["Puppy Honey", "S", [], `C`],
    ["Puppy Honey 2", "S", [], `C`],
    ["Reminders", "S", [], `C`],
    ["Room Alone 1", "S", [], `C`],
    ["Room Alone 2", "S", [], `C`],
    ["Secret Seven", "S", [], `C`],
    ["Slam Dance", "S", [], `C`],
    ["SOTUS", "S", ["I"], `C`],
    ["SOTUS S", "S", [], `C`],
    ["The Cupid Series 1: Hunsa", "S", ["I"], `C`],
    ["The Cupid Series 2: Ork Suek", "S", [], `C`],
    ["The Cupid Series 3: Online", "S", ["N"], `C`],
    ["The Cupid Series 4: Loob Kom", "S", ["N"], `C`],
    ["The Cupid Series 5: Sorn Ruk", "S", ["N"], `C`],
    ["The Cupid Series 6: Sorn Kol", "S", ["I", "N"], `C`],
    ["The Cupid Series 8: Prab Marn", "S", ["S", "I"], `C`],
    ["The Effect", "S", [], `C`],
    ["The Gifted", "S", [], `C`],
    ["The Judgment", "S", [], `C`],
    ["The Shipper", "S", ["H"], `C`],
    ["The Star Beside the Moon", "S", [], `C`],
    ["The Warp Effect", "S", [], `C`],
    ["Thicha", "S", [], `C`],
    ["Tử Thần Ngọt Ngào", "S", ["I"], `C`],
    ["To Sir, With Love", "S", [], `C`],
    ["Ugly Duckling: Boy's Paradise", "S", ["N"], `C`],
    ["Ugly Duckling: Don't", "S", ["S", "I"], `C`],
    ["Ugly Duckling: Pity Girl", "S", ["S"], `C`],
    ["Ugly Duckling: Perfect Match", "S", ["I"], `C`],
    ["U Prince 2: Gentle Vet", "S", ["N"], `C`],
    ["U Prince 3: Lovely Geologist", "S", [], `C`],
    ["U Prince 4: Badass Baker", "S", [], `C`],
    ["U Prince 5: Absolute Economist", "S", [], `C`],
    ["U Prince 6: Foxy Pilot", "S", ["I"], `C`],
    ["U Prince 7: Playful Comm-Arts", "S", [], `C`],
    ["U Prince 8: Extroverted Humanist", "S", [], `C`],
    ["U Prince 9: Single Lawyer", "S", ["I"], `C`],
    ["U Prince 10: Crazy Artist", "S", [], `C`],
    ["U Prince 11: Badly Politics", "S", ["I"], `C`],
    ["Wandee Goodday", "S", [], `C`],
    ["Who Are You", "S", [], `C`],
    ["Why R U?", "S", ["I"], `C`],
    ["Wolf The Series", "S", [], `C`],
    ["YYY The Series", "S", ["H"], `C`],
    ["En of Love: Mechanic Love", "S", [], `C`],
  ],
  VIETNAMESE: [
    ["5 Anh Em Siêu Nhân", "S", [], `C`],
    ["Anh Em Siêu Quậy", "S", [], `C`],
    ["Bạn Gái Tôi Là Sếp", "M", [], `C`],
    ["Bảo Mẫu Siêu Quậy", "M", [], `C`],
    ["Bảo Mẫu Siêu Quậy 2", "M", [], `C`],
    ["Bằng Chứng Vô Hình", "M", [], `C`],
    ["Bỗng Dưng Muốn Khóc", "S", [], `C`],
    ["Bố Già", "M", [], `C`],
    ["Bố Tôi Là Cao Thủ", "M", [], `C`],
    ["Cái Giá Của Hạnh Phúc", "S", [], `C`],
    ["Chiếc Giường Chia Đôi", "S", [], `C`],
    ["Chàng Vợ Của Em", "M", [], `C`],
    ["Chị Dâu", "M", [], `C`],
    ["Chiến Dịch Chống Ế", "S", [], `C`],
    ["Chờ Em Đến Ngày Mai", "M", [], `C`],
    ["Cô Gái Đến Từ Hôm Qua", "M", [], `C`],
    ["Cô Nàng Bướng Bỉnh", "S", [], `C`],
    ["Công Chúa Teen Và Ngũ Hổ Tướng", "M", [], `C`],
    ["Cổng Mặt Trời", "S", [], `C`],
    ["Cuộc Chiến Hoa Hồng", "S", [], `C`],
    ["Dân Chơi Không Sợ Con Rơi", "M", [], `C`],
    ["Đất Rừng Phương Nam", "M", [], `C`],
    ["Em Chưa 18", "M", [], `C`],
    ["Em Là Bà Nội Của Anh", "M", [], `C`],
    ["Em Là Của Em", "M", [], `C`],
    ["Giải Cứu Thần Chết", "M", [], `C`],
    ["Giải Mã Tình Anh", "S", [], `C`],
    ["Gia Sư Nữ Quái", "M", [], `C`],
    ["Gia Đình Phép Thuật", "S", [], `C`],
    ["Hai Muối", "M", [], `C`],
    ["Hai Người Vợ", "S", [], `C`],
    ["Hello Cô Ba", "M", [], `C`],
    ["Hoa Ngũ Sắc", "S", [], `C`],
    ["Hoán Đổi", "M", [], `C`],
    ["Khi Ta 16", "S", [], `C`],
    ["Kim Chi Cà Pháo", "S", ["H"], `C`],
    ["Kính Vạn Hoa", "S", [], `C`],
    ["Làm Giàu Với Ma", "M", [], `C`],
    ["Lật Mặt 5: 48H", "M", [], `C`],
    ["Lật Mặt 6: Tấm Vé Định Mệnh", "M", [], `C`],
    ["Lật Mặt 7: Một Điều Ước", "M", [], `C`],
    ["La Mo6", "S", [], `C`],
    ["Love House Season 1", "S", [], `C`],
    ["Lục Lạc Huyền Bí", "S", [], `C`],
    ["Ma Dai", "M", [], `C`],
    ["Mai", "M", [], `C`],
    ["Maika", "M", [], `C`],
    ["Mệnh Lệnh Hoa Hồng", "S", [], `C`],
    ["Năm Sau Con Lại Về", "M", [], `C`],
    ["Nắng", "M", [], `C`],
    ["Nắng 2", "M", [], `C`],
    ["Ngày Mai Mai Cưới", "M", [], `C`],
    ["Ngày Nảy Ngày Nay", "M", [], `C`],
    ["Ngày Xửa Ngày Xưa", "S", [], `C`],
    ["Nhà Bà Nữ", "M", [], `C`],
    ["Nghề Siêu Dễ", "M", [], `C`],
    ["Người Bất Tử", "M", [], `C`],
    ["Người Mẹ Nhí", "S", [], `C`],
    ["Người Vợ Cuối Cùng", "M", [], `C`],
    ["Nhà Có 5 Nàng Tiên", "M", [], `C`],
    ["Nụ Hôn Bạc Tỷ", "M", [], `C`],
    ["Nụ Hôn Thần Chết", "M", [], `C`],
    ["Pororo Và Những Người Bạn", "A", [], `C`],
    ["Pupu Chacha", "A", [], `C`],
    ["Quý Cô Thừa Kế", "M", [], `C`],
    ["Quý Cô Thừa Kế 2", "M", [], `C`],
    ["Rô Bốt Trái Cây", "A", [], `C`],
    ["Tài Chó Điên", "W", [], `C`],
    ["Tèo Em", "M", [], `C`],
    ["Thanh Sói", "M", [], `C`],
    ["Thiên Thần Hộ Mệnh", "M", ["X"], `C`],
    ["Tiệm Bánh Hoàng Tử Bé", "S", [], `C`],
    ["Tiệm Bánh Hoàng Tử Bé 2", "S", [], `C`],
    ["Tôi Thấy Hoa Vàng Trên Cỏ Xanh", "M", [], `C`],
    ["Trà Xanh Đấu Siêu Lừa", "S", [], `C`],
    ["Trạng Tí Phiêu Lưu Kí", "M", [], `C`],
    ["Trên Bàn Nhậu, Dưới Bàn Mưu", "M", [], `C`],
    ["Trúng Số", "S", [], `C`],
    ["Tử Chiến Trên Không", "M", [], `C`],
    ["Xóm Trọ 3D", "M", [], `C`],
    ["Yêu", "M", [], `C`],
    ["Yêu Từ Thuở Nào", "S", [], `C`],
  ],
  CHINESE_TAIWANESE: [
    ["Accidentally In Love", "S", [], `P,ep 20`],
    ["Anh Dã 3+1", "S", ["I"], `C`],
    ["Arsenal Military Academy", "S", ["S", "I"], `C`],
    ["Bromance", "S", [], `C`],
    ["Chào Em Như Hoa", "S", ["I"], `C`],
    ["Công Chúa Ori", "A", [], `C`],
    ["Đấu Trường Yoyo", "A", [], `C`],
    ["Định Mệnh Anh Yêu Em", "S", ["I"], `C`],
    ["Đời Sống Chợ Đêm", "S", [], `C`],
    ["HIStory1: Obsessed", "S", ["I"], `C`],
    ["HIStory1: Stay Away from Me", "S", ["I"], `C`],
    ["HIStory2: Crossing the Line", "S", [], `C`],
    ["HIStory3: Make Our Days Count", "S", ["I"], `C`],
    ["Hoàng Tử Ếch", "S", ["I"], `C`],
    ["I Married the Anti-Fan", "M", ["I"], `C`],
    ["Lớp Trưởng Đại Nhân", "S", ["I"], `C`],
    ["Let's Talk About Chu", "S", [], `C`],
    ["Love Because of the Height", "M", [], `C`],
    ["Một Ngày Biến Thành Em", "S", ["I"], `C`],
    ["Mr. Pride and Ms. Prejudice", "M", [], `C`],
    ["Nghỉ, Nghiêm, Anh Yêu Em", "S", ["S", "I"], `C`],
    ["Our Shining Days", "S", [], `C`],
    ["Our Time", "M", ["I", "N"], `C`],
    ["Pucca", "A", [], `C`],
    ["Sáng Tạo Danh 2021", "V", [], `C`],
    ["Sấm Chớp Và Tốc Độ", "A", [], `C`],
    ["Go Go Princess", "S", ["I"], `C`],
    ["Thần Hổ Thiên Nhãn", "A", [], `C`],
    ["Xin Chào Kiều An", "S", ["I"], `C`],
  ],
  JAPANESE: [
    ["5 Centimeters Per Second", "M", [], `C`],
    ["A Silent Voice", "M", [], `C`],
    ["Chú Mèo Máy Rocky", "A", [], `C`],
    ["Classroom of the Elite", "A", [], `P,season 1`],
    ["Conan", "A", [], `C`],
    ["Doraemon", "A", [], `C`],
    ["Horimiya", "A", [], `C`],
    ["Howl's Moving Castle", "M", [], `C`],
    ["Kaguya-Sama: Love is War", "A", [], `P,season 2`],
    ["Maid Sama", "A", ["N"], `C`],
    ["Naruto", "A", [], `C`],
    ["Naruto Shippuden", "A", [], `C`],
    ["Pokemon", "A", [], `C`],
    ["ReLIFE", "A", [], `C`],
    ["Sakamoto Days", "A", [], `P,season 1`],
    ["Spy X Family", "A", [], `P,season 2`],
    ["Shin - Cậu Bé Bút Chì", "A", [], `C`],
    ["The Disastrous Life of Saiki K.", "A", [], `C`],
    ["Vùng Đất Linh Hồn", "M", [], `C`],
    ["Your Lie in April", "A", [], `C`],
    ["Your Name", "M", [], `C`],
  ],
  AMERICAN: [
    ["#RealityHigh", "M", [], `C`],
    ["10 Things I Hate About You", "M", [], `C`],
    ["13 Reasons Why", "S", [], `C`],
    ["17 Again", "M", [], `C`],
    ["A Good Place", "S", [], `C`],
    ["A Nice Girl Like You", "M", [], `C`],
    ["Aladdin", "M", [], `C`],
    ["Alex Strangelove", "M", [], `C`],
    ["Alice in Wonderland", "M", [], `C`],
    ["Alvin and the Chipmunks 1", "M", [], `C`],
    ["Alvin and the Chipmunks 2", "M", [], `C`],
    ["Alvin and the Chipmunks 3", "M", [], `C`],
    ["Always Be My Maybe", "M", [], `C`],
    ["Avatar", "M", [], `C`],
    ["Avatar: The Way of Water", "M", [], `C`],
    ["Avatar: Fire and Ashes", "M", [], `C`],
    ["Avengers: Endgame", "M", [], `C`],
    ["Avengers: Infinity War", "M", [], `C`],
    ["Beef", "S", [], `C`],
    ["Ben 10", "A", [], `C`],
    ["Big Hero 6", "M", [], `C`],
    ["Blended", "M", [], `C`],
    ["Bridgerton", "S", [], `P,season 3`],
    ["Cẩm Nang Của Ned", "S", [], `C`],
    ["Catdog", "A", [], `C`],
    ["Carry On", "M", [], `C`],
    ["Christopher and Robin", "M", [], `C`],
    ["Cinderella", "M", [], `C`],
    ["Click", "M", [], `C`],
    ["Coco", "M", [], `C`],
    ["Courage", "A", [], `C`],
    ["Degrassi: New Class", "S", [], `C`],
    ["Dictator", "M", [], `C`],
    ["Do Revenge", "M", [], `C`],
    ["Dumplin", "M", [], `C`],
    ["Elemental", "M", [], `C`],
    ["Encanto", "M", [], `C`],
    ["Enchanted", "M", [], `C`],
    ["Everything Everywhere All At Once", "M", [], `C`],
    ["Falling Inn Love", "M", [], `C`],
    ["Family Switch", "M", [], `C`],
    ["Flatliners", "M", [], `C`],
    ["Fifty Shades of Black", "M", ["H"], `C`],
    ["Finding Nemo", "M", [], `C`],
    ["Finding Dory", "M", [], `C`],
    ["Fish Hook", "A", [], `C`],
    ["Focus", "M", [], `C`],
    ["FRIENDS", "S", ["H"], `C`],
    ["Friends from College", "S", [], `C`],
    ["Ginny and Georgia", "S", [], `P,season 2`],
    ["Good Doctor", "S", [], `C`],
    ["Handsome Devil", "M", [], `C`],
    ["Happy Gilmore", "M", [], `C`],
    ["Hard Feelings", "M", [], `C`],
    ["Harry Potter 1: Sorcerer's Stone", "M", [], `C`],
    ["Harry Potter 2: Chamber of Secrets", "M", [], `C`],
    ["Harry Potter 3: Prisoner of Azkaban", "M", [], `C`],
    ["Harry Potter 4: Goblet of Fire", "M", [], `C`],
    ["Harry Potter 5: Order of the Phoenix", "M", [], `C`],
    ["Harry Potter 6: Half-Blood Prince", "M", [], `C`],
    ["Harry Potter 7: Deathly Hallows", "M", [], `C`],
    ["Harry Potter 20th Anniversary", "M", [], `C`],
    ["HeartBreak High", "S", [], `P,season 1`],
    ["Heated Rivalry", "S", [], `C`],
    ["Hotel Transylvania", "M", [], `C`],
    ["Hotel Transylvania 2", "M", [], `C`],
    ["Hotel Transylvania 3", "M", [], `C`],
    ["How to Be Single", "M", [], `C`],
    ["Insatiable", "S", [], `C`],
    ["Inside Out", "M", [], `C`],
    ["Irish Wish", "M", [], `C`],
    ["Iron Man", "M", [], `C`],
    ["Isn't It Romantic", "M", [], `C`],
    ["IT", "M", [], `C`],
    ["IT Chapter 2", "M", [], `C`],
    ["Jingle Jangle", "M", [], `C`],
    ["Jurassic World: Dominion", "M", [], `C`],
    ["Just Friends", "M", [], `C`],
    ["Kissing Booth", "M", [], `C`],
    ["Knocked Up", "M", [], `C`],
    ["Kung Fu Panda", "M", [], `C`],
    ["Leap Year", "M", [], `C`],
    ["Life as We Know It", "M", [], `C`],
    ["Life of the Party", "M", [], `C`],
    ["Lilo and Stitch", "M", [], `C`],
    ["Little Man", "M", [], `C`],
    ["Joker", "M", [], `C`],
    ["Love, Guaranteed", "M", [], `C`],
    ["Lucifer", "S", [], `P,season 4`],
    ["Luca", "M", [], `C`],
    ["Maleficent", "M", [], `C`],
    ["Maleficent: Mistress of Evil", "M", [], `C`],
    ["Mall Cop", "M", [], `C`],
    ["Mean Girls", "M", [], `C`],
    ["Middle School: Worst Years", "M", [], `C`],
    ["Mismatched", "S", [], `C`],
    ["Money Heist", "S", [], `C`],
    ["Monsters, Inc", "M", [], `C`],
    ["Monsters University", "M", [], `C`],
    ["Mr. Bean", "S", [], `C`],
    ["Murder Mystery", "M", [], `C`],
    ["My Fake Boyfriend", "M", [], `C`],
    ["My Perfect Romance", "M", [], `C`],
    ["Naomi & Ely's No Kiss List", "M", [], `C`],
    ["No Hard Feelings", "M", [], `C`],
    ["New Girl", "S", [], `C`],
    ["Night at the Museum", "M", [], `C`],
    ["Night at the Museum 2", "M", [], `C`],
    ["Nine Lives", "M", [], `C`],
    ["Oggy and the Cockroaches", "A", [], `C`],
    ["Old Dads", "M", [], `C`],
    ["On My Block", "S", [], `C`],
    ["Our Little Secret", "M", [], `C`],
    ["Penelope", "M", [], `C`],
    ["Peter Pan", "M", [], `C`],
    ["Phineas and Ferb", "A", [], `C`],
    ["Phù Thủy Xứ Waverly", "S", [], `C`],
    ["Pippi Cô Bé Tất Dài", "S", [], `C`],
    ["Players", "M", [], `C`],
    ["Pride and Prejudice", "M", [], `C`],
    ["Plus One", "M", [], `C`],
    ["Prince of Peoria", "S", [], `C`],
    ["Puppy Love", "M", [], `C`],
    ["Queenpins", "M", [], `C`],
    ["Ratatouille", "M", [], `C`],
    ["Ralph Breaks the Internet", "M", [], `C`],
    ["Red Notice", "M", [], `C`],
    ["Red White and Royal Blue", "M", [], `C`],
    ["Schitt's Creek", "S", ["H", "N"], `C`],
    ["Sex Education", "S", [], `C`],
    ["Sextuplets", "M", [], `C`],
    ["Shallow Hal", "M", [], `C`],
    ["Shameless", "S", [], `C`],
    ["She's Out of My League", "M", [], `C`],
    ["She's the Man", "M", [], `C`],
    ["Sing", "M", [], `C`],
    ["Sing 2", "M", [], `C`],
    ["Single All The Way", "M", [], `C`],
    ["Sky High", "M", [], `C`],
    ["Sleeping with Other People", "M", [], `C`],
    ["Smiley", "S", [], `C`],
    ["Someone Borrowed", "M", [], `C`],
    ["Something Borrowed", "M", [], `C`],
    ["Spider-Man", "M", [], `C`],
    ["Spider-Man 2", "M", [], `C`],
    ["Spider-Man 3", "M", [], `C`],
    ["Spider-Man: Far From Home", "M", [], `C`],
    ["Spider-Man: Homecoming", "M", [], `C`],
    ["Spider-Man: No Way Home", "M", [], `C`],
    ["Spider-Man: Across the Spider-Verse", "M", [], `C`],
    ["Spider-Man: Into the Spider-Verse", "M", [], `C`],
    ["Spy Kids: All the Time", "M", [], `C`],
    ["Straight Up", "M", [], `C`],
    ["Stepmom", "M", [], `C`],
    ["Still Time", "M", [], `C`],
    ["Tangled", "M", [], `C`],
    ["The 10 Year Plan", "M", [], `C`],
    ["The 40 Year Old Virgin", "M", [], `C`],
    ["The Amazing Spider-Man", "M", [], `C`],
    ["The Amazing Spider-Man 2", "M", [], `C`],
    ["The Boss Baby", "M", [], `C`],
    ["The Boss Baby: Family Business", "M", [], `C`],
    ["The Blade Runner", "M", [], `C`],
    ["The Break-Up", "M", [], `C`],
    ["The Change-Up", "M", [], `C`],
    ["The Conjuring", "M", [], `C`],
    ["The DUFF", "M", [], `C`],
    ["The Edge of Seventeen", "M", [], `C`],
    ["The Family Plan", "M", [], `C`],
    ["The Founder", "M", [], `C`],
    ["The Glass Dome", "S", [], `C`],
    ["The Half of It", "M", [], `C`],
    ["The Healing Power of Dude", "S", [], `C`],
    ["The Incredibles", "M", [], `C`],
    ["The Incredibles 2", "M", [], `C`],
    ["The Knight Before Christmas", "M", [], `C`],
    ["The Lion King", "M", [], `C`],
    ["The Lost City", "M", [], `C`],
    ["The Mindy Project", "S", [], `C`],
    ["The Old Guard", "M", [], `C`],
    ["The Other Guys", "M", [], `C`],
    ["The Out-Laws", "M", [], `C`],
    ["The Perfect Date", "M", [], `C`],
    ["The Politicians", "S", [], `C`],
    ["The Princess and the Frog", "M", [], `C`],
    ["The Princess Switch", "M", [], `C`],
    ["The Princess Switch 2", "M", [], `C`],
    ["The Proposal", "M", [], `C`],
    ["The Secret Life of Pets", "M", [], `C`],
    ["The Secret Life of Pets 2", "M", [], `C`],
    ["The Secret Life of Walter Mitty", "M", [], `C`],
    ["The To Do List", "M", [], `C`],
    ["The Ugly Truth", "M", [], `C`],
    ["The Umbrella Academy", "S", [], `P,season 3`],
    ["The Unlisted", "S", [], `C`],
    ["Tom and Jerry", "A", [], `C`],
    ["Toy Story", "M", [], `C`],
    ["Toy Story 2", "M", [], `C`],
    ["Toy Story 3", "M", [], `C`],
    ["Toy Story 4", "M", [], `C`],
    ["Uncharted", "M", [], `C`],
    ["Uncoupled", "S", [], `P,season 1`],
    ["Up", "M", [], `C`],
    ["Valeria", "S", [], `C`],
    ["Wall-E", "M", [], `C`],
    ["Walk of Shame", "M", [], `C`],
    ["When We First Met", "M", [], `C`],
    ["Weapons", "M", [], `C`],
    ["Wedding Season", "M", [], `C`],
    ["Wednesday", "S", [], `P,season 1`],
    ["We're the Millers", "M", [], `C`],
    ["White Chicks", "M", [], `C`],
    ["Wonder Woman 1984", "M", [], `C`],
    ["Work It", "M", [], `C`],
    ["Working Mom", "S", [], `C`],
    ["Wreck-It Ralph", "M", [], `C`],
    ["You", "S", [], `P,season 5`],
    ["Your Place or Mine", "M", [], `C`],
    ["You're Not Invited to My Bat Mitzvah", "M", [], `C`],
    ["XO, Kitty", "S", [], `C`],
    ["Zootopia", "M", [], `C`],
    ["Zootopia 2", "M", [], `C`],
  ],
};

async function seed() {
  const client = await pool.connect();
  try {
    console.log("🌱 Starting seed...");

    // Clear existing data in correct order
    await client.query("DELETE FROM show_keywords");
    await client.query("DELETE FROM shows");
    await client.query("DELETE FROM keywords");

    // Insert keywords
    const keywords = [
      { code: "S", label: "SML", color: "#a855f7" },
      { code: "H", label: "HM", color: "#f59e0b" },
      { code: "I", label: "IB", color: "#ef4444" },
      { code: "N", label: "Sweet", color: "#ec4899" },
      { code: "X", label: "Horror", color: "#6b7280" },
    ];

    const keywordIdMap = {};
    for (const kw of keywords) {
      const res = await client.query(
        "INSERT INTO keywords (code, label, color) VALUES ($1, $2, $3) RETURNING id",
        [kw.code, kw.label, kw.color],
      );
      keywordIdMap[kw.code] = res.rows[0].id;
    }
    console.log("✅ Keywords inserted");

    // Insert shows
    let showCount = 0;
    for (const [country, shows] of Object.entries(RAW)) {
      for (const [title, typeCode, kwCodes, statusRaw] of shows) {
        let status = "COMPLETED";
        let currentEp = null;

        if (statusRaw.startsWith("P")) {
          status = "PARTIALLY_WATCHED";
          currentEp = statusRaw.split(",")[1]?.trim() || null;
        } else if (statusRaw === "W") {
          status = "PLAN_TO_WATCH";
        }

        const type = TYPE_MAP[typeCode] || "SERIES";

        const res = await client.query(
          `INSERT INTO shows (title, country, type, status, current_ep)
           VALUES ($1, $2, $3, $4, $5) RETURNING id`,
          [title, country, type, status, currentEp],
        );

        const showId = res.rows[0].id;

        for (const code of kwCodes) {
          if (keywordIdMap[code]) {
            await client.query(
              "INSERT INTO show_keywords (show_id, keyword_id) VALUES ($1, $2)",
              [showId, keywordIdMap[code]],
            );
          }
        }

        showCount++;
      }
    }

    console.log(`✅ ${showCount} shows inserted`);
    console.log("🎉 Seed complete!");
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
